# Generated by Django 5.2.6 on 2025-10-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_sent',
            new_name='sent',
        ),
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(),
        ),
    ]
