# Generated by Django 5.2.6 on 2025-10-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0002_rename_sender_message_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
