# Generated by Django 5.2.7 on 2025-10-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hearts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='tada',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('graduation', 'Graduation'), ('anniversary', 'Anniversary'), ('other', 'Other')], max_length=50),
        ),
    ]
