# Generated by Django 5.2.7 on 2025-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0008_comment_hearts_comment_tada_comment_thumbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tada',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='thumbs',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
    ]
