# Generated by Django 5.2.7 on 2025-10-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postbox', '0009_remove_comment_tada_remove_comment_thumbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_event_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('graduation', 'Graduation'), ('anniversary', 'Anniversary'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
